### PR TITLE
fix in TailoredExperiences functions

### PR DESCRIPTION
**Pull request by lcaturelli**

### CODE REVIEW

**Comment by farag2** [comment]
Thanks. I've already found that "bug". Will add in the the 5.1 version!

**Comment by lcaturelli** [comment]
👍😉

**Comment by farag2** [comment]
Now trying to make the script translatable using

```powershell
Import-LocalizedData
```
👍

**Comment by lcaturelli** [comment]
Thank you! You did an excellent job modularizing in functions too, keep it up! 💪

**Pull request closed without merging**
