### PR TITLE
Added Spanish translation (es-ES)

### PR DESCRIPTION
**Pull request by AnxoMJ**

### CODE REVIEW

**Comment by farag2** [comment]
Nice!

**Comment by farag2** [comment]
@AnxoMJ

```powershell
ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = The script supports Windows 10 x64 only
UnsupportedOSBuild                     = The script supports Windows 10 2004/20H1 versions and higher
ControlledFolderAccessDisabled         = Controlled folder access disabled

# ScheduledTasks
ScheduledTasks                         = Scheduled tasks

# OneDrive
OneDriveUninstalling                   = Uninstalling OneDrive...
OneDriveNotEmptyFolder                 = "{0}" folder is not empty. Delete it manually
OneDriveFileSyncShell64dllBlocked      = "{0}" is blocked. Delete it manually
OneDriveInstalling                     = OneDrive is installing...
OneDriveDownloading                    = Downloading OneDrive... ~33 MB

# TempPath
ClearFolder                            = Delete all files in "{0}" folder
FilesBlocked                           = The following files are being blocked by third-party party apps `nRemove them manually and continue
TempNotEmpty                           = "{0}" folder is not empty. Clear it manually

# WindowsFeature
WindowsFeaturesTitle                   = Windows features

# WindowsCapabilities
Patient                                = Please wait...
FODWindowTitle                         = Optional features (FODv2)

# WindowsSandbox
EnableHardwareVT                       = Enable Virtualization in UEFI

# SetUserShellFolderLocation
UserShellFolderNotEmpty                = Some files left in the "{0}" folder `nMove them manually to a new location
RetrievingDrivesList                   = Retrieving drives list...

DesktopDriveSelect                     = Select the drive within the root of which the Desktop folder will be created
DocumentsDriveSelect                   = Select the drive within the root of which the Documents folder will be created
DownloadsDriveSelect                   = Select the drive within the root of which the Downloads folder will be created
MusicDriveSelect                       = Select the drive within the root of which the Music folder will be created
PicturesDriveSelect                    = Select the drive within the root of which the Pictures folder will be created
VideosDriveSelect                      = Select the drive within the root of which the Videos folder will be created

DesktopFRequest                        = Would you like to change the location of the Desktop folder?
DocumentsRequest                       = Would you like to change the location of the Documents folder?
DownloadsRequest                       = Would you like to change the location of the Downloads folder?
MusicRequest                           = Would you like to change the location of the Music folder?
PicturesRequest                        = Would you like to change the location of the Pictures folder?
VideosRequest                          = Would you like to change the location of the Videos folder?

DesktopFolderSelect                    = Select a folder for the Desktop folder
DocumentsFolderSelect                  = Select a folder for the Documents folder
DownloadsFolderSelect                  = Select a folder for the Downloads folder
MusicFolderSelect                      = Select a folder for the Music folder
PicturesFolderSelect                   = Select a folder for the Pictures folder
VideosFolderSelect                     = Select a folder for the Videos folder

DesktopDefaultFolder                   = Would you like to change the location of the Desktop folder to the default value?
DocumentsDefaultFolder                 = Would you like to change the location of the Documents folder to the default value?
DownloadsDefaultFolder                 = Would you like to change the location of the Downloads folder to the default value?
MusicDefaultFolder                     = Would you like to change the location of the Music folder to the default value?
PicturesDefaultFolder                  = Would you like to change the location of the Pictures folder to the default value?
VideosDefaultFolder                    = Would you like to change the location of the Videos folder to the default value?

# ReservedStorage
ReservedStorageIsInUse                 = This operation is not supported when reserved storage is in use `nPlease wait for any servicing operations to complete and then try again later

# Shortcuts pinning
syspinDownloading                      = Downloading syspin... ~20 KB
ShortcutPinning                        = The "{0}" shortcut is being pinned to Start

# UninstallUWPApps
UninstallUWPForAll                     = Uninstall for All Users
UninstallUWPTitle                      = UWP Packages to Uninstall

# WSL
WSLUpdateDownloading                   = Downloading the Linux kernel update package... ~14 MB
WSLUpdateInstalling                    = Installing the Linux kernel update package...

# SetAppGraphicsPerformance
GraphicsPerformanceTitle               = Graphics performance preference
GraphicsPerformanceRequest             = Would you like to set the graphics performance setting of an app of your choice to "High performance"?
GraphicsPerformanceFilter              = *.exe|*.exe|All Files (*.*)|*.*

# CleanUpTask
CleanUpTaskToast                       = Cleaning up unused Windows files and updates starts in a minute
CleanUpTaskDescription                 = Cleaning up unused Windows files and updates using built-in Disk cleanup app

# TempTask/SoftwareDistributionTask
FolderTaskDescription                  = The "{0}" folder cleaning

# AddProtectedFolders
ProtectedFoldersTitle                  = Controlled folder access
ProtectedFoldersRequest                = Would you like to enable Controlled folder access and specify the folder that Microsoft Defender will protect from malicious apps and threats?

# RemoveProtectedFolders
ProtectedFoldersListRemoved            = Removed folders

# AddAppControlledFolder
AppControlledFolderTitle               = Controlled folder access
AppControlledFolderRequest             = Would you like to specify an app that is allowed through Controlled Folder access?
AppControlledFolderFilter              = *.exe|*.exe|All Files (*.*)|*.*

# RemoveAllowedAppsControlledFolder
AllowedAppsControlledFolderListRemoved = Removed allowed apps

# AddDefenderExclusionFolder
DefenderExclusionFolderTitle           = Microsoft Defender
DefenderExclusionFolderRequest         = Would you like to specify a folder to be excluded from Microsoft Defender malware scans?

# RemoveDefenderExclusionFolders
DefenderExclusionFoldersListRemoved    = Excluded folders removed

# AddDefenderExclusionFile
AddDefenderExclusionFileRequest        = Would you like to specify a file to be excluded from Microsoft Defender malware scans?
AddDefenderExclusionFileFilter         = All Files (*.*)|*.*

# RemoveDefenderExclusionFiles
RemoveDefenderExclusionFilesList       = Excluded files removed

# EventViewerCustomView
EventViewerCustomViewName              = Process Creation
EventViewerCustomViewDescription       = Process creation and command-line auditing events

# Refresh
RestartWarning                         = Be sure to restart your PC

# Errors
ErrorsLine                             = Line
ErrorsFile                             = File
ErrorsMessage                          = Errors/Warnings

# Misc
Add                                    = Add
Change                                 = Change
Continue                               = Continue
DialogBoxOpening                       = Displaying the dialog box...
Disable                                = Disable
Enable                                 = Enable
FolderSelect                           = Slect a folder
FilesWontBeMoved                       = Files will not be moved
NoData                                 = Nothing to display
NoInternetConnection                   = No Internet connection
Select                                 = Select
Skip                                   = Skip
Skipped                                = Skipped
Uninstall                              = Uninstall
'@
```

Please translate the latest version.

**Comment by AnxoMJ** [comment]
```
ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Este script solo soporta Windows 10 x64
UnsupportedOSBuild                     = Este script solo soporta Windows 10 2004/20H1 o superior
ControlledFolderAccessDisabled         = Acceso a carpetas controlado desactivado

# ScheduledTasks
ScheduledTasks                         = Tareas programadas

# OneDrive
OneDriveUninstalling                   = Desinstalando OneDrive...
OneDriveNotEmptyFolder                 = El directorio "{0}" no está vacío. Elimínelo manualmente
OneDriveFileSyncShell64dllBlocked      = "{0}" está bloqueado. Elimínelo manualmente
OneDriveInstalling                     = OneDrive se está instalando...
OneDriveDownloading                    = Descargando OneDrive... ~33 MB

# TempPath
ClearFolder                            = Elimine todos los archivos en la carpeta "{0}"
FilesBlocked                           = Los siguientes archivos están siendo bloqueados por una aplicación de terceros `nElimínelos manualmente y continúe
TempNotEmpty                           = La carpeta "{0}" no está vacía. Límpiela manualmente
# WindowsFeature
WindowsFeaturesTitle                   = Características de Windows

# WindowsCapabilities
Patient                                = Por favor espere...
FODWindowTitle                         = Características opcionales (FODv2)

# WindowsSandbox
EnableHardwareVT                       = Activar virtualización en UEFI

# SetUserShellFolderLocation
UserShellFolderNotEmpty                = Quedan algunos archivos en  la carpeta "{0}" `nMuévalos manualmente a la nueva ubicación
RetrievingDrivesList                   = Recuperando lista de unidades de disco...

DesktopDriveSelect                     = Selecciona la raíz del disco en la cual se creará la carpeta del Escritorio
DocumentsDriveSelect                   = Selecciona la raíz del disco en la cual se creará la carpeta de Documentos
DownloadsDriveSelect                   = Selecciona la raíz del disco en la cual se creará la carpeta de Descargas
MusicDriveSelect                       = Selecciona la raíz del disco en la cual se creará la carpeta de Música
PicturesDriveSelect                    = Selecciona la raíz del disco en la cual se creará la carpeta de Imágenes
VideosDriveSelect                      = Selecciona la raíz del disco en la cual se creará la carpeta de Vídeos

DesktopFRequest                        = Quieres cambiar la ubicación de la carpeta del Escritorio?
DocumentsRequest                       = Quieres cambiar la ubicación de la carpeta de Documentos?
DownloadsRequest                       = Quieres cambiar la ubicación de la carpeta de Descargas?
MusicRequest                           = Quieres cambiar la ubicación de la carpeta de Música?
PicturesRequest                        = Quieres cambiar la ubicación de la carpeta de Imágenes?
VideosRequest                          = Quieres cambiar la ubicación de la carpeta de Vídeos?

DesktopFolderSelect                    = Selecciona una carpeta para la carpeta del Escritorio
DocumentsFolderSelect                  = Selecciona una carpeta para la carpeta de Documentos
DownloadsFolderSelect                  = Selecciona una carpeta para la carpeta de Descargas
MusicFolderSelect                      = Selecciona una carpeta para la carpeta de Música
PicturesFolderSelect                   = Selecciona una carpeta para la carpeta de Imágenes
VideosFolderSelect                     = Selecciona una carpeta para la carpeta de Vídeos

DesktopDefaultFolder                   = Quieres cambiar la ubicación de la carpeta del Escritorio por la de defecto?
DocumentsDefaultFolder                 = Quieres cambiar la ubicación de la carpeta de Documentos por la de defecto?
DownloadsDefaultFolder                 = Quieres cambiar la ubicación de la carpeta de Descargas por la de defecto?
MusicDefaultFolder                     = Quieres cambiar la ubicación de la carpeta de Música por la de defecto?
PicturesDefaultFolder                  = Quieres cambiar la ubicación de la carpeta de Imágenes por la de defecto?
VideosDefaultFolder                    = Quieres cambiar la ubicación de la carpeta de Vídeos por la de defecto?

# ReservedStorage
ReservedStorageIsInUse                 = Esta operación no está disponible cuando el almacenamiento reservado está en uso`nPorfavor, espere a que se complete alguna operación de algún servicio e inténtelo de nuevo más tarde

# Shortcuts pinning
syspinDownloading                      = Descargando syspin... ~20 KB
ShortcutPinning                        = El acceso directo "{0}" se está acoplando al inicio

# UninstallUWPApps
UninstallUWPForAll                     = Desinstalar para todos los usuarios
UninstallUWPTitle                      = Paquetes UWP a desinstalar

# WSL
WSLUpdateDownloading                   = Descargando el paquete de actualización del kernel de Linux... ~14 MB
WSLUpdateInstalling                    = Instalando el paquete de actualización del kernel de Linux...

# SetAppGraphicsPerformance
GraphicsPerformanceTitle               = Preferencia de rendimiento de gráficos
GraphicsPerformanceRequest             = Quieres establecer el nivel de rendimiento de gráficos a "Alto rendimiento" en alguna aplicación?
GraphicsPerformanceFilter              = *.exe|*.exe|Todos los Archivos (*.*)|*.*

# CleanUpTask
CleanUpTaskToast                       = Limpiando archivos no usados y actualizaciones de Windows comienza en un minuto
CleanUpTaskDescription                 = Limpiando archivos de Windows no usados y actualizaciones usando la aplicación de limpieza de disco incorporada

# TempTask/SoftwareDistributionTask
FolderTaskDescription                  = Limpieza de la carpeta "{0}"

# AddProtectedFolders
ProtectedFoldersTitle                  = Acceso controlado a carpetas
ProtectedFoldersRequest                = Quieres añadir control de acceso a carpeta y especificar que carpeta Microsoft Defender protegerá de aplicaciones maliciosas y amenazas?

# RemoveProtectedFolders
ProtectedFoldersListRemoved            = Carpetas eliminadas

# AddAppControlledFolder
AppControlledFolderTitle               = Acceso controlado a carpetas
AppControlledFolderRequest             = Quieres especificar una aplicación para que sea permitida a través del acceso controlado de carpetas?
AppControlledFolderFilter              = *.exe|*.exe|Todos los Archivos (*.*)|*.*

# RemoveAllowedAppsControlledFolder
AllowedAppsControlledFolderListRemoved = Eliminar aplicaciones permitidas

# AddDefenderExclusionFolder
DefenderExclusionFolderTitle           = Microsoft Defender
DefenderExclusionFolderRequest         = Quieres especificar una carpeta para ser excluida por Microsoft Defender?

# RemoveDefenderExclusionFolders
DefenderExclusionFoldersListRemoved    = Quitadas carpetas excluidas

# AddDefenderExclusionFile
AddDefenderExclusionFileRequest        = Quieres especificar un archivo para ser excluido por Microsoft Defender?
AddDefenderExclusionFileFilter         = *.exe|*.exe|Todos los Archivos (*.*)|*.*

# RemoveDefenderExclusionFiles
RemoveDefenderExclusionFilesList       = Quitados archivos excluidos

# EventViewerCustomView
EventViewerCustomViewName              = Creación de procesos
EventViewerCustomViewDescription       = Creación de procesos y eventos de auditoria de línea de comandos

# Refresh
RestartWarning                         = Asegúrese de reiniciar su PC

# Errors
ErrorsLine                             = Línea
ErrorsFile                             = Archivo
ErrorsMessage                          = Errores/Advertencias

# Misc
Add                                    = Añadir
Change                                 = Cambiar
Continue                               = Continuar
DialogBoxOpening                       = Mostrando caja de diálogo...
Disable                                = Desactivar
Enable                                 = Activar
FolderSelect                           = Seleccione una carpeta
FilesWontBeMoved                       = Los archivos no se moverán
NewUserShellFolderLocation             = Nueva ubicación: "{0}"
NoData                                 = Nada que mostrar
NoInternetConnection                   = No hay conexión a Internet
Select                                 = Seleccionar
Skip                                   = Omitir
Skipped                                = Omitido
Uninstall                              = Desinstalar
'@
```
 @farag2  done, I hope it's ok

**Comment by farag2** [comment]
God bless you!!

I am just waiting for the translators to send their translation variants. The 5.3 is done! 10 436 lines.

**Comment by AnxoMJ** [comment]
Nice, looking forward for it

**Pull request closed without merging**
